### PR TITLE
Update travis

### PR DESCRIPTION
**Pull request by pana1990**

### CODE REVIEW

**Comment by SilverFire** [comment]
Failed to pass test on PHP7.

It relates to a Samrty code, that is out of Yii scope:
```php
     return $this->smarty->registered_plugins[$plugin_type][$tag][0][0]->$function[1]($new_args, $this);
```
[Source](https://github.com/smarty-php/smarty/blob/v3.1.27/libs/sysplugins/smarty_internal_templatecompilerbase.php#L555)

It is fixed in the @dev version:
```php
return $this->smarty->registered_plugins[$plugin_type][$tag][0][0]->{$function[1]}($new_args, $this);
```
[Source](https://github.com/smarty-php/smarty/blob/master/libs/sysplugins/smarty_internal_templatecompilerbase.php#L572)

I've created in issue in Smarty repo: https://github.com/smarty-php/smarty/issues/113

**Comment by samdark** [comment]
:+1:

**Comment by pana1990** [comment]
:+1:

**Comment by SilverFire** [comment]
Smarty tagged a PHP7-compatible release.

**Comment by SilverFire** [comment]
Merged! Thank you!

**Pull request merged**
